DROP DATABASE IF EXISTS EMPRESA;
CREATE DATABASE EMPRESA;
USE EMPRESA;

CREATE TABLE DEPARTAMENTO(
COD_DEP SMALLINT,
NOME_DEP VARCHAR(50));
DESC DEPARTAMENTO;

ALTER TABLE DEPARTAMENTO CHANGE COD_DEP DEP_PK SMALLINT PRIMARY KEY;
DESC DEPARTAMENTO;

ALTER TABLE DEPARTAMENTO ADD DESCRICAO_DEP VARCHAR(100);
DESC DEPARTAMENTO;


CREATE TABLE FUNCIONARIO(
COD_FUNC SMALLINT PRIMARY KEY,
NOME_FUNC VARCHAR(50),
DEPARTAMENTO_FUNC SMALLINT,
FOREIGN KEY (DEPARTAMENTO_FUNC) REFERENCES DEPARTAMENTO (DEP_PK));
DESC FUNCIONARIO;

CREATE TABLE PAGAMENTOS(
DATA_PAG DATE,
VALOR_PAG DECIMAL(10,2),
CATEGORIA_PAG SMALLINT,
FUNC_PAG SMALLINT,
FOREIGN KEY (FUNC_PAG) REFERENCES FUNCIONARIO (COD_FUNC));
DESC PAGAMENTOS;

CREATE TABLE CATEGORIA(
NUMERO_CAT SMALLINT PRIMARY KEY,
DESCRICAO_CAT VARCHAR(100),
LIMITE_CAT SMALLINT);
DESC CATEGORIA;

ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_CATEGORIA FOREIGN KEY (CATEGORIA_PAG) REFERENCES CATEGORIA (NUMERO_CAT);
DESC PAGAMENTOS;

INSERT INTO DEPARTAMENTO (DEP_PK, NOME_DEP, DESCRICAO_DEP)
VALUES
(1, 'Administrativo', 'Departamento administrativo'),
(2, 'Financeiro', 'Departamento financeiro'),
(3, 'Recursos Humanos', 'Departamento de recursos humanos'),
(4, 'Tecnologia', 'Departamento de tecnologia'),
(5, 'Vendas', 'Departamento comercial e vendas');

INSERT INTO FUNCIONARIO (COD_FUNC, NOME_FUNC, DEPARTAMENTO_FUNC)
VALUES
(1, 'Joao Silva', 1),
(2, 'Maria Souza', 2),
(3, 'Carlos Oliveira', 3),
(4, 'Ana Santos', 4),
(5, 'Pedro Costa', 5),
(6, 'Jota Tavares', 5);

INSERT INTO CATEGORIA (NUMERO_CAT, DESCRICAO_CAT, LIMITE_CAT)
VALUES
(1, 'Salario', 5000),
(2, 'Bonus', 2000),
(3, 'Comissao', 3000),
(4, 'Hora Extra', 1500),
(5, 'Premiacao', 2500);

INSERT INTO PAGAMENTOS (DATA_PAG, VALOR_PAG, CATEGORIA_PAG, FUNC_PAG)
VALUES
('2026-09-01', 3500.00, 1, 1),
('2026-09-02', 1200.00, 2, 2),
('2026-09-03', 1800.00, 3, 3),
('2026-09-04', 750.00, 4, 4),
('2026-09-05', 2000.00, 5, 5);


SELECT COUNT(*) AS TOTAL_FUNCIONARIO
FROM FUNCIONARIO;

SELECT NOME_FUNC AS FUNCIONARIO, VALOR_PAG AS VALOR
FROM PAGAMENTOS, FUNCIONARIO
WHERE COD_FUNC = FUNC_PAG;


SELECT
NOME_DEP AS DEPARTAMENTO, COUNT(*) AS FUNCIONARIOS
FROM FUNCIONARIO, DEPARTAMENTO 
WHERE DEPARTAMENTO_FUNC = DEP_PK
GROUP BY DEPARTAMENTO_FUNC;


