DROP DATABASE IF EXISTS INDUSTRIA;
CREATE DATABASE INDUSTRIA;
USE INDUSTRIA;

CREATE TABLE DEPARTAMENTO(
NOME VARCHAR(80) PRIMARY KEY,
ORCAMENTO DECIMAL(10, 2),
GERENTE INT
);

CREATE TABLE FUNCIONARIO(
MATRICULA INT PRIMARY KEY,
NOME VARCHAR(80),
SALARIO DECIMAL(10,2),
INICIO DATE,
DEPARTAMENTO VARCHAR(80)
);

CREATE TABLE PROJETO(
NUMERO SMALLINT PRIMARY KEY,
ORCAMENTO DECIMAL(10, 2),
GERENTE INT,
FOREIGN KEY(GERENTE) REFERENCES FUNCIONARIO(MATRICULA)
);

CREATE TABLE TRABALHA(
FUNCIONARIO INT,
PROJETO SMALLINT,
HORAS_SEMANAIS TIME,
PRIMARY KEY(FUNCIONARIO, PROJETO),
FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(MATRICULA),
CONSTRAINT FOREIGN KEY(PROJETO) REFERENCES PROJETO(NUMERO)
);
CREATE TABLE PROJETO_DEPARTAMENTO(
DEPARTAMENTO VARCHAR(80),
PROJETO SMALLINT,
PRIMARY KEY(DEPARTAMENTO, PROJETO),
FOREIGN KEY(DEPARTAMENTO) REFERENCES DEPARTAMENTO(NOME),
FOREIGN KEY(PROJETO) REFERENCES PROJETO(NUMERO)
);

CREATE TABLE FORNECEDOR(
ID SMALLINT PRIMARY KEY,
NOME VARCHAR(50)
);

CREATE TABLE COMPONENTE(
NOME VARCHAR(50),
FORNECEDOR SMALLINT,
PRIMARY KEY(NOME,FORNECEDOR),
FOREIGN KEY(FORNECEDOR) REFERENCES FORNECEDOR(ID)
);

CREATE TABLE COMP_PROJ(
COMPONENTE VARCHAR(50),
DEPARTAMENTO VARCHAR(80),
PROJETO SMALLINT,
QUANTIDADE INT,
PRIMARY KEY(COMPONENTE, DEPARTAMENTO, PROJETO),
FOREIGN KEY(COMPONENTE) REFERENCES COMPONENTE(NOME),
FOREIGN KEY(DEPARTAMENTO) REFERENCES DEPARTAMENTO(NOME),
FOREIGN KEY(PROJETO) REFERENCES PROJETO(NUMERO)
);


ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_GERENTE FOREIGN KEY (GERENTE) REFERENCES FUNCIONARIO(MATRICULA);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(NOME);
