USE SI;

SELECT AUTOR.NOME, TITULO 
FROM AUTOR_LIVRO, AUTOR, LIVRO 
WHERE AUTOR_LIVRO.MATRICULA = AUTOR.MATRICULA AND AUTOR_LIVRO.CODIGO = LIVRO.CODIGO 
ORDER BY NOME, TITULO;

SELECT EDITORA.NOME 
FROM EDITORA, LIVRO, AUTOR, AUTOR_LIVRO 
WHERE EDITORA.CODIGO = LIVRO.EDITORA  AND LIVRO.CODIGO = AUTOR_LIVRO.CODIGO  AND AUTOR_LIVRO.MATRICULA = AUTOR.MATRICULA  AND AUTOR.NOME = 'Ana da Silva';

SELECT MAX(PRECO) PRECO 
FROM LIVRO, EDITORA 
WHERE EDITORA = EDITORA.CODIGO AND EDITORA.NOME = 'MIRANDELA EDITORA' AND ASSUNTO = 'P';

SELECT TITULO, EDITORA.NOME EDITORA 
FROM LIVRO, EDITORA 
WHERE EDITORA = EDITORA.CODIGO AND PRECO < 50;

SELECT AUTOR.NOME NOME, CPF, LIVRO.TITULO TITULO
FROM AUTOR, LIVRO, AUTOR_LIVRO 
WHERE AUTOR_LIVRO.MATRICULA = AUTOR.MATRICULA AND AUTOR_LIVRO.CODIGO = LIVRO.CODIGO AND NACIONALIDADE = 'BRASILEIRA' AND DATANASC <= '1950-01-01' 
ORDER BY AUTOR.NOME, LIVRO.TITULO;

SELECT CPF, AUTOR.NOME NOME, MAX(PRECO)
FROM AUTOR, LIVRO, AUTOR_LIVRO 
WHERE AUTOR.MATRICULA = AUTOR_LIVRO.MATRICULA AND AUTOR_LIVRO.CODIGO = LIVRO.CODIGO
GROUP BY AUTOR.CPF, AUTOR.NOME
HAVING MAX(LIVRO.PRECO) > 50.00;

SELECT AUTOR.NOME NOME, EDITORA.NOME EDITORA, COUNT(*) QUANTIDADE
FROM AUTOR, AUTOR_LIVRO, LIVRO, EDITORA
WHERE AUTOR.MATRICULA = AUTOR_LIVRO.MATRICULA AND LIVRO.CODIGO = AUTOR_LIVRO.CODIGO AND EDITORA.CODIGO = LIVRO.EDITORA
GROUP BY AUTOR.MATRICULA, AUTOR.NOME, EDITORA.CODIGO, EDITORA.NOME
HAVING COUNT(*) >=2;

SELECT DESCRICAO, COUNT(*) QUANTIDADE
FROM ASSUNTO, LIVRO
WHERE ASSUNTO.SIGLA = LIVRO.ASSUNTO
GROUP BY ASSUNTO.SIGLA, ASSUNTO.DESCRICAO
HAVING COUNT(*) >=10;
